_meta_: {}
bundle_root: /work/ze116753/TDT4265_StarterCode_2024/final_final/with_pretrain/ASOCA/dints
ckpt_path: $@bundle_root + '/model_fold' + str(@fold)
data_file_base_dir: /work/ze116753/TDT4265_StarterCode_2024/data_flat
data_list_file_path: /work/ze116753/TDT4265_StarterCode_2024/final_final/model1_auto3dseg/data.json
finetune:
  activate_finetune: true
  overwrite:
    adapt_valid_mode: true
    early_stop_mode: false
    learning_rate: 0.2
    lr_scheduler: {_target_: torch.optim.lr_scheduler.PolynomialLR, optimizer: $@training#optimizer,
      power: 0.5, total_iters: $@training#num_epochs // @training#num_epochs_per_validation
        + 1}
    num_epochs: 2000
    num_epochs_per_validation: 1
  pretrained_ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt'
fold: 0
infer: {ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt',
  data_list_key: testing, fast: true, log_output_file: $@bundle_root + '/model_fold'
    + str(@fold) + '/inference.log', output_path: $@bundle_root + '/prediction_' +
    @infer#data_list_key, save_prob: false}
show_cache_progress: false
stats_summary:
  image_stats:
    shape:
      mean: [512.0, 512.0, 215.25714285714287]
  n_cases: 35
training:
  adapt_valid_mode: true
  adapt_valid_num_epochs_per_validation: [2, 4, 2]
  adapt_valid_progress_percentages: [10, 40, 70]
  amp: true
  auto_scale_allowed: true
  cache_rate: 0
  data_list_key: null
  early_stop_delta: 0
  early_stop_mode: true
  early_stop_patience: 40
  epoch_divided_factor: 36
  input_channels: 1
  learning_rate: 0.2
  log_output_file: $@bundle_root + '/model_fold' + str(@fold) + '/training.log'
  loss: {_target_: DiceFocalLoss, batch: true, include_background: true, sigmoid: $not
      @training#softmax, smooth_dr: 1.0e-05, smooth_nr: 1.0e-05, softmax: $@training#softmax,
    squared_pred: true, to_onehot_y: $@training#softmax}
  lr_scheduler: {_target_: torch.optim.lr_scheduler.PolynomialLR, optimizer: $@training#optimizer,
    power: 0.5, total_iters: $@training#num_epochs // @training#num_epochs_per_validation
      + 1}
  num_cache_workers: 10
  num_epochs: 502
  num_epochs_per_validation: 1
  num_images_per_batch: 6
  num_patches_per_image: 10
  num_patches_per_iter: 5
  num_sw_batch_size: null
  num_workers: 4
  num_workers_validation: 2
  optimizer: {_target_: torch.optim.SGD, lr: '@training#learning_rate', momentum: 0.9,
    weight_decay: 4.0e-05}
  output_classes: 2
  overlap_ratio: 0.625
  overlap_ratio_train: 0.125
  patch_size: [96, 96, 96]
  patch_size_valid: [96, 96, 96]
  random_seed: 0
  resample_to_spacing: [0.3945310116, 0.3945310116, 0.625]
  softmax: true
  sw_input_on_cpu: false
  train_cache_rate: $@training#cache_rate
  transforms: {resample_to_spacing: $@training#resample_to_spacing}
  valid_at_orig_resolution_at_last: true
  valid_at_orig_resolution_only: false
  validate_cache_rate: $@training#cache_rate
validate: {ckpt_name: $@bundle_root + '/model_fold' + str(@fold) + '/best_metric_model.pt',
  data_list_key: null, log_output_file: $@bundle_root + '/model_fold' + str(@fold)
    + '/validation.log', output_path: $@bundle_root + '/prediction_fold' + str(@fold),
  save_mask: true}
