_meta_: {}
image_key: image
label_key: label
transforms_validate:
  _target_: Compose
  transforms:
  - _target_: Compose
    transforms:
    - {_target_: LoadImaged, dtype: $np.float32, image_only: false, keys: '@image_key'}
    - {_target_: LoadImaged, dtype: $np.uint8, image_only: false, keys: '@label_key'}
  - _target_: EnsureChannelFirstd
    keys: ['@image_key', '@label_key']
  - _target_: Compose
    transforms:
    - {_target_: ScaleIntensityRanged, a_max: 612.03701171875, a_min: -194.05437711079915,
      b_max: 1.0, b_min: 0.0, clip: true, keys: '@image_key'}
    - _target_: CropForegroundd
      end_coord_key: null
      keys: ['@image_key', '@label_key']
      source_key: '@image_key'
      start_coord_key: null
  - _target_: Orientationd
    axcodes: RAS
    keys: ['@image_key', '@label_key']
  - _target_: Spacingd
    align_corners: [true, true]
    keys: ['@image_key', '@label_key']
    mode: [bilinear, nearest]
    pixdim: $@training#transforms#resample_to_spacing
  - _target_: CastToTyped
    dtype: [$torch.float32, $torch.uint8]
    keys: ['@image_key', '@label_key']
  - _target_: EnsureTyped
    keys: ['@image_key', '@label_key']
    track_meta: false
