max_lr: 0.01
weight_decay: 0.0001
momentum: 0.9
max_epochs: 500
batch_size: 4

in_channels: 3
num_classes: 2
use_pretrained_weights: true

test_model: false
checkpoint_path: #checkpoints/*****.ckpt used for 
early_stopping_patience: 10
num_workers: 2
check_val_every_n_epoch: 3
devices: auto
enable_progress_bar: False

wandb_project: ASOCA
# wandb_experiment_name: ASOCA_idun
wandb_experiment_name: modelOnSpleen

train_split_ratio: 0.8
data_root: ./data
checkpoint_folder: ./checkpoints/

# data_dir: /cluster/work/felixzr/TDT4265_StarterCode_2024/project/code/data.json
data_dir: /cluster/work/felixzr/TDT4265_StarterCode_2024/project/code/data_spleen.json


