name: tdt4265
dependencies:
  - pip
  - python=3.10
  - pip:
      # - torchmetrics <= 0.5.0
      - tensorrt
      - nib
      - tensorflow
      - tensorboard
      - fire
      - timm
      - einops
      - nnunet
      - fvcore
      - resnest
      - SimpleITK
      - nbconvert==7.14.2
      - numpy==1.26.3
      - pandoc==2.3
      - scikit-learn==1.4.0
      - torch==2.1.2
      - torchvision==0.16.2
      - tqdm==4.66.1
      - matplotlib==3.8.2
      - scikit-image==0.22.0
      - notebook
      - lightning
      - wandb
      - munch
      - jupyter
      - monai
      - pynrrd
      - pandas==1.2.4
      - pyvista
      - scikit-image


# install:
# $ conda env create -f environment.yml

# update:
# $ conda env update --name tdt4265 --file environment.yml --prune

# activate:
# $ conda activate tdt4265
      

